[package]
name = "ble-scan-reporter-demo-gateway"
version = "0.1.0"
edition = "2024"

[dependencies]
ariel-os = { path = "build/imports/ariel-os/src/ariel-os", features = [
  "tcp",
  "mdns",
  "dns",
  "time",
  "uart",
  "sensors",
  "external-interrupts",
] }
ariel-os-boards = { path = "build/imports/ariel-os/src/ariel-os-boards" }
ariel-os-nrf91-gnss = { path = "build/imports/ariel-os/src/ariel-os-nrf91-gnss", features = [
  "defmt",
] }
ariel-os-gnss-time-extension = { path = "build/imports/ariel-os/src/ariel-os-gnss-time-extension", features = [
  "defmt",
] }
embassy-futures = { version = "0.1.1" }
heapless = { version = "0.8", features = ["serde"] }
reqwless = { version = "0.13.0", default-features = true, features = [
  "embedded-tls",
] }
rand_core = "0.6.4"
serde_json = { version = "1.0.145", default-features = false, features = [
  "alloc",
] }
common-types = { path = "../common-types" }
linkme = { version = "0.3.32" }
embedded-io-async = "0.6.1"
postcard = { version = "1.1.3", features = ["use-defmt"] }

embassy-sync = { version = "0.6.2" }
embassy-nrf = { version = "0.3.1" }

nrfxlib-sys = "=2.9.2"
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(context, values(any()))',
] }
